local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 10.0
   publish_frequency: 2.0
   width: 1        # make window small so robot tends to follow global path
   height: 1
   resolution: 0.05
   static_map: false
   rolling_window: true
